#
# WellCart Platform
#
# @copyright  Copyright (c) 2016 WellCart Development Team    http://wellcart.org/
# @license    http://www.opensource.org/licenses/BSD-3-Clause New BSD License
#
service_name: travis-ci
coverage_clover: ./tests/report/clover.xml
json_path: ./tests/report/coveralls.json
