#
# WellCart Platform
#
# @copyright  Copyright (c) 2016 WellCart Development Team    http://wellcart.org/
# @license    http://www.opensource.org/licenses/BSD-3-Clause New BSD License
#
imports:
    - php
checks:
    php:
        code_rating: true
        duplication: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
tools:
    external_code_coverage:
        timeout: 2100 # Timeout in seconds.
        runs: 3
    php_code_coverage: true
    php_sim: true
    php_changetracking: true
    php_mess_detector: true    
    php_pdepend: true
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            paths: ['src']
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]